# Configuration for Vale Linter GitHub App
# https://github.com/warrenbuckley/vale-linter

Vale:
  Enabled: true

  Paths:
    Configuration: '.vale.ini'
    Styles: 'styles/'

  Success:
    Header: 'Documentation looks good!'
    Message: 'No style issues found in this PR.'
    ShowImage: false

  Error:
    Header: 'Style issues found'
    Message: 'Please review the suggestions below to improve documentation quality.'
    ShowImage: false
